# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on: 
  push: 
      branches: [ "main" ]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: My first step
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci  # or yarn install
      
      - name: Install pm2 globally
        run: npm install -g pm2  # Install pm2 globally
      
      - name: Restart using pm2
        run: pm2 restart all

# name: Node.js CI/CD

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: self-hosted
    # strategy:
    #   matrix:
    #     node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    # steps:
    # - uses: actions/checkout@v3
    # - name: Use Node.js
    #   - run: pm2 restart all
      # uses: actions/setup-node@v3
      # with:
      #   node-version: ${{ matrix.node-version }}
        # cache: 'npm'
    # - run: npm ci
    # - run: |
    #     touch .env
    #     echo "${{ secrets.PROD_ENV_FILE }}" > .env
    